version: '2'

services:
  app:
    image: 'high-arts-university:latest'
    build:
      context: .
    container_name: app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/highartsuniversity
      - SPRING_DATASOURCE_USERNAME=highartsuniversity
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8080:8080"

  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=highartsuniversity
      - POSTGRES_PASSWORD=password